### ISSUE TITLE
cartes 

### ISSUE THREAD

**Issue by AudreyChob** [ActiveZ/cnam-monopoly#9]
- [x] Tirer une carte 
- [x] Mélanger les cartes
- [x] Suppression de la carte tirée du tableau 
- [x] Particularités sur les maisons / hôtels (calculs réparations) 
- [x] Gains / pertes
- [x] Modifications de position 
- [x] Libéré de prison 
- [x] Payer amende ou tirer carte chance (à traiter )
- [x] Problèmes de faillites quand il faut payer des amendes ou frais

**Comment by ActiveZ** [comment]
fait
